import { AppTheme } from '@styles/theme'
import { createUseStyles } from 'react-jss'

export const useStyles = createUseStyles(
	(theme: AppTheme) => ({
		card: {
			position: 'relative',
			display: 'flex',
			flexDirection: 'column',
			gap: 12,
			padding: '18px 18px 16px',
			borderRadius: theme.radius.lg,
			background: `linear-gradient(135deg, ${theme.colors.surfacePrimary}, ${theme.colors.surfaceAccentBlue})`,
			boxShadow: theme.shadow.window,
			border: `1px solid rgba(148, 163, 184, 0.35)`,
			overflow: 'hidden',
		},
		banner: {
			position: 'absolute',
			top: 8,
			left: '50%',
			transform: 'translateX(-50%)',
			padding: '6px 14px',
			borderRadius: theme.radius.full,
			fontSize: 13,
			display: 'flex',
			alignItems: 'center',
			gap: 8,
			boxShadow: theme.shadow.name,
			border: `1px solid rgba(148, 163, 184, 0.7)`,
			animation: '$bannerIn 0.22s ease-out',
			backdropFilter: 'blur(6px)',
			zIndex: 1,
		},
		bannerRoundStart: {
			extend: 'banner',
			background:
				'linear-gradient(135deg, rgba(96, 165, 250, 0.9), rgba(129, 140, 248, 0.9))',
			color: '#e5e7eb',
		},
		bannerResult: {
			extend: 'banner',
			background:
				'linear-gradient(135deg, rgba(192, 132, 252, 0.95), rgba(244, 114, 182, 0.95))',
			color: '#f9fafb',
		},
		bannerInfo: {
			extend: 'banner',
			background: 'rgba(15, 23, 42, 0.9)',
			color: theme.colors.textAccentSoft,
		},
		bannerIcon: {
			fontSize: 14,
		},
		bannerText: {
			fontSize: 13,
			fontWeight: 600,
			whiteSpace: 'nowrap',
		},
		headerRow: {
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
			gap: 12,
			marginTop: 10,
		},
		statusBadge: {
			padding: '6px 12px',
			borderRadius: theme.radius.full,
			fontSize: 13,
			fontWeight: 600,
			textTransform: 'uppercase',
			letterSpacing: '0.08em',
			background: 'rgba(15, 23, 42, 0.85)',
			color: theme.colors.textAccentSoft,
			border: `1px solid rgba(148, 163, 184, 0.5)`,
		},
		statusBadgeRunning: {
			extend: 'statusBadge',
			background: 'rgba(22, 163, 74, 0.18)',
			borderColor: 'rgba(34, 197, 94, 0.8)',
			color: '#bbf7d0',
		},
		statusBadgeFinished: {
			extend: 'statusBadge',
			background: 'rgba(147, 51, 234, 0.16)',
			borderColor: 'rgba(192, 132, 252, 0.9)',
			color: '#f5d0fe',
		},
		statusBadgeIdle: {
			extend: 'statusBadge',
			background: 'rgba(15, 23, 42, 0.7)',
			borderColor: 'rgba(148, 163, 184, 0.5)',
			color: theme.colors.textAccentSoft,
		},
		title: {
			margin: 0,
			fontSize: 18,
			fontWeight: 600,
			color: theme.colors.textAccentSoft,
		},
		description: {
			margin: 0,
			fontSize: 13,
			color: theme.colors.textSecondary,
			whiteSpace: 'pre-line',
		},
		bodyRow: {
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
			gap: 16,
			flexWrap: 'wrap',
		},
		timerPill: {
			minWidth: 120,
			padding: '8px 14px',
			borderRadius: theme.radius.full,
			background: 'rgba(15, 23, 42, 0.92)',
			border: `1px solid rgba(148, 163, 184, 0.6)`,
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center',
			rowGap: 2,
		},
		timerLabel: {
			fontSize: 11,
			textTransform: 'uppercase',
			letterSpacing: '0.12em',
			color: theme.colors.textSecondary,
		},
		timerValue: {
			fontSize: 22,
			fontVariantNumeric: 'tabular-nums',
			fontWeight: 700,
			color: '#e5e7eb',
		},
		timerDanger: {
			color: '#fecaca',
		},
		timerInactive: {
			opacity: 0.6,
		},
		resultBlock: {
			marginTop: 10,
			paddingTop: 10,
			borderTop: '1px dashed rgba(148, 163, 184, 0.6)',
			display: 'flex',
			flexDirection: 'column',
			gap: 6,
		},
		resultTitle: {
			fontSize: 12,
			textTransform: 'uppercase',
			letterSpacing: '0.12em',
			color: theme.colors.textSecondary,
		},
		resultRow: {
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'space-between',
			gap: 12,
			flexWrap: 'wrap',
		},
		resultNumber: {
			padding: '6px 12px',
			borderRadius: theme.radius.full,
			background: 'rgba(15, 23, 42, 0.9)',
			border: `1px solid rgba(252, 211, 77, 0.9)`,
			color: '#fef3c7',
			fontSize: 14,
			fontWeight: 600,
		},
		resultWinner: {
			padding: '6px 12px',
			borderRadius: theme.radius.full,
			background: 'rgba(15, 23, 42, 0.9)',
			border: `1px solid rgba(190, 242, 100, 0.9)`,
			color: '#ecfccb',
			fontSize: 14,
			fontWeight: 600,
		},
		resultSub: {
			fontSize: 12,
			color: theme.colors.textSecondary,
		},
		playersRow: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'flex-start',
			gap: 4,
		},
		playersTitle: {
			fontSize: 12,
			color: theme.colors.textSecondary,
		},
		playersBadges: {
			display: 'flex',
			gap: 8,
			flexWrap: 'wrap',
		},
		playerBadge: {
			padding: '4px 10px',
			borderRadius: theme.radius.full,
			fontSize: 12,
			background: 'rgba(15, 23, 42, 0.85)',
			color: theme.colors.textAccentSoft,
			border: `1px solid rgba(148, 163, 184, 0.45)`,
		},
		playerBadgeHighlight: {
			extend: 'playerBadge',
			background: 'rgba(59, 130, 246, 0.18)',
			borderColor: 'rgba(96, 165, 250, 0.9)',
		},
		'@keyframes bannerIn': {
			from: {
				opacity: 0,
				transform: 'translateX(-50%) translateY(-6px)',
			},
			to: {
				opacity: 1,
				transform: 'translateX(-50%) translateY(0)',
			},
		},
	}),
	{ name: 'GameStatus' }
)

